### ISSUE TITLE
Image Overhaul

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/docker-baseimage-web#14]
So for our upcoming magento and contao project I want to have an overhaul of our docker image. 
After some quick analysis here's what I want to change:
- The Baseimage will get stripped by a lot:
  - remove ssh service (we will only mount volumes and shell access is done via docker exec)
  - remove mysql, apache, php (php cli will still be there for composer) and use other container instead for easy swtiching (mysql, mariadb, php5 vs 7, apache vs. nginx)
  - phing will be gone. maybe replaced with gulp / node but I don't think that's necessary since that stuff wil only run in the ide
  - phpbrew will be removed completely (versions will be useable by other containers. see above)
- update Ubuntu to 16 

In Step 2 I want to have our own 
- proxy system
- dns system

With docker-composer we can create easy maintainable startup files. We will put examples in here. 

/cc @ctsmedia/cts-developer

**Comment by mvscheidt** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre e-Mail. Ich bin vom 03.10. bis einschließlich 09.10. nicht erreichbar und erst am 10.10. wieder im Hause.

In dieser Zeit werden meine Mails nicht gelesen. Bitte wenden Sie sich in dringenden Fällen an meine Kollegen.

-per Mail: info@cts-media.eu / d.schwiperich@cts-media.eu / t.siefert@cts-media.eu

-telefonisch: +49 (0)221 – 16 88 14 00


Mit freundlichen Grüßen,

Mike vom Scheidt

-----------------

Dear Sir or Madam,

thank you for your message. I am currently out of the office and will be back on Monday, October 10, 2016.

If you need immediate assistance please contact the office:

-E-Mail: info@cts-media.eu / d.schwiperich@cts-media.eu / t.siefert@cts-media.eu

-Telephone: +49 (0)221 – 16 88 14 00


Kind regards,

Mike vom Scheidt
