### ISSUE TITLE
Move composer and php cli to php container

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/docker-baseimage-web#17]
The web / apache container should not have php cli because it could lead to conflicts if php cli version differs to php containers version. 

So we should move composer and php cli to php container. That way we always have the same php version

/cc @ctsmedia/cts-developer

**Comment by thorstensiefertcts** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre e-Mail. Ich bin vom 10.04.2017 bis einschließlich 21.04.2017 nicht erreichbar und erst am 24.04.2017 wieder im Hause.

In dieser Zeit werden meine Mails nicht gelesen. Bitte wenden Sie sich in dringenden Fällen an meine Kollegen.

-per Mail: info@cts-media.eu

-telefonisch: +49 (0)221 – 16 88 14 00


Mit freundlichen Grüßen,

Thorsten A. Siefert

-----------------

Dear Sir or Madam,

thank you for your message. I am currently out of the office and will be back on  April 24th  2017.

If you need immediate assistance please contact the office:

-E-Mail: info@cts-media.eu

-Telephone: +49 (0)221 – 16 88 14 00


Kind regards,

Thorsten A. Siefert
