### ISSUE TITLE
Update xdebug 

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/docker-baseimage-web#19]
the version string is not valid anymore in 
https://github.com/ctsmedia/docker-baseimage-web/blob/master/php/Dockerfile#L25

```
RUN pecl install xdebug \
    && echo 'zend_extension = /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so' >> /usr/local/etc/php/php.ini
```

Leads to message on every php call (only visible in cli mode). Can be annoying too
```
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
```

and needs to be replaced. we also should used a fixes version during pecl install

still thinking of not having xdebug as default installed because of performance. but usually should not have a big impact

@ctsmedia/cts-developer any opinions

**Comment by DanielSchwiperich** [comment]
pushed to docker hub. repull to get changes

@ctsmedia/cts-developer

**Comment by mvscheidt** [comment]
I don't think we should care about performance in our docker containers, in my opinion it doesn't matter if the page is rendered in 300ms or 500ms - the fact that we can use xdebug for more detailed debugging outweighs the performance downsides in my opinion.

Performance in Docker would only really matter if our goal is to assess "real life" performance on production-like setups before deploying to production. But that is only really useful if we have tools for statistics over longer periods of time (e.g. as part of the pipelines)

**Comment by DanielSchwiperich** [comment]
Only linux user can talk that way 😁 
on mac docker is way slower than our remote machines. every second counts 😉 

But it's already to late. Update your images and xdebug is enabled
