### ISSUE TITLE
Add git to php container

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/docker-baseimage-web#22]
if you run composer, sometimes for private packages it needs git. but git is not installed / available yet. 

Should we add it @ctsmedia/cts-developer ?

(our local docker:update task can fail of it)

**Comment by mvscheidt** [comment]
Should be installed. I just got this again and Now have to fix it manually

* Branch *X* - have Version 1.1 of some-bundle installed
* Switch to Branch *Y* where you still use some-bundle 1.0
* try to use our docker::update Task - it fails with

```
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 1 update, 0 removals
  - Updating some-bundle(1.1.0 => 1.0.0): 
                                            
  [RuntimeException]                        
  Failed to execute git show-ref --head -d  
  sh: 1: git: not found      
```
